/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_;
import sys.crudTable;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author ALYA NORMAIDA
 */
public class FrameDaftarPerkara extends javax.swing.JFrame {

String judulkolom[] = {"id", "nik_client", "nama_client", "nama_penanggung_jawab", "penanggung_jawab_kasus", "perkara", "status", "tindakan_hukum", "hasil_tindakan"};
int lebarkolom[] = {150, 300, 200, 100, 100, 100};
String SQL = "SELECT *FROM daftar_perkara";

private crudTable myObject;
public FrameDaftarPerkara() {
        initComponents();
        this.setLocationRelativeTo(null);
        myObject = new crudTable();
        myObject.settingJudulTabel(Tabledaftar_perkara, judulkolom);
        myObject.settingLebarKolom(Tabledaftar_perkara, lebarkolom);
        myObject.tampilTabel(Tabledaftar_perkara, SQL, judulkolom);
    /**
     * Creates new form FrameDaftarPerkara
     */
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnik_client = new javax.swing.JTextField();
        txtnama_client = new javax.swing.JTextField();
        txtnama_penanggung_jawab = new javax.swing.JTextField();
        txtpenanggung_jawab_kasus = new javax.swing.JTextField();
        txtperkara = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txttindakan_hukum = new javax.swing.JTextField();
        txthasil_tindakan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledaftar_perkara = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("nik_client");

        jLabel3.setText("nama_client");

        jLabel4.setText("nama_penanggung_jawab");

        jLabel5.setText("penanggung_jawab_kasus");

        jLabel6.setText("perkara");

        jLabel7.setText("status");

        jLabel8.setText("tindakan_hukum");

        jLabel9.setText("hasil_tindakan");

        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtnik_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnik_clientActionPerformed(evt);
            }
        });

        txthasil_tindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasil_tindakanActionPerformed(evt);
            }
        });

        Tabledaftar_perkara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabledaftar_perkara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabledaftar_perkaraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabledaftar_perkara);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txthasil_tindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(txttindakan_hukum, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtperkara, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtid)
                                        .addComponent(txtnik_client)
                                        .addComponent(txtnama_client)
                                        .addComponent(txtnama_penanggung_jawab)
                                        .addComponent(txtpenanggung_jawab_kasus, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)
                        .addGap(0, 233, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnik_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnama_penanggung_jawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpenanggung_jawab_kasus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtperkara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttindakan_hukum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txthasil_tindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
        String primaryKey = "id";
        String primaryValue = txtid.getText();
        String[] fieldToUpdate = {"id","nik_client", "nama_client","nama_penanggung_jawab","penanggung_jawab_kasus", "perkara", "status", "tindakan_hukum", "hasil_tindakan"};
        
        String[] newValue = {
        txtid.getText(),
        txtnik_client.getText(),
        txtnama_client.getText(),
        txtnama_penanggung_jawab.getText(),
        txtpenanggung_jawab_kasus.getText(),
        txtperkara.getText(),
        txtstatus.getText(),
        txttindakan_hukum.getText(),
        txthasil_tindakan.getText()
        };

        myObject.UbahDinamis("daftar_perkara", primaryKey, primaryValue, fieldToUpdate, newValue);
        myObject.tampilTabel(Tabledaftar_perkara, SQL, judulkolom);
        } catch (Exception e) {
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnik_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnik_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnik_clientActionPerformed

    private void txthasil_tindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasil_tindakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasil_tindakanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
           String id = txtid.getText();
           String nik_client = txtnik_client.getText();
           String nama_client = txtnama_client.getText();
           String nama_penanggung_jawab = txtnama_penanggung_jawab.getText();
           String penanggung_jawab_kasus = txtpenanggung_jawab_kasus.getText();
           String perkara = txtperkara.getText();
           String status = txtstatus.getText();
           String tindakan_hukum = txttindakan_hukum.getText();
           String hasil_tindakan = txthasil_tindakan.getText();
           String[] daftar_perkara = {"id", "nik_client", "nama_client","nama_penanggung_jawab","penanggung_jawab_kasus", "perkara", "status", "tindakan_hukum", "hasil_tindakan"};
           String[] isiTable = {id, nik_client, nama_client,nama_penanggung_jawab,penanggung_jawab_kasus, perkara, status, tindakan_hukum, hasil_tindakan};
           myObject.SimpanDinamis("daftar_perkara", daftar_perkara, isiTable);
           myObject.tampilTabel(Tabledaftar_perkara, SQL, judulkolom);
        } catch (Exception e) {
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {
            String primaryKey = "id";
            String primaryValue = txtid.getText();
            
            txtid.setText("");
            txtnik_client.setText("");
            txtnama_client.setText("");
            txtnama_penanggung_jawab.setText("");
            txtpenanggung_jawab_kasus.setText("");
            txtperkara.setText("");
            txtstatus.setText("");
            txttindakan_hukum.setText("");
            txthasil_tindakan.setText("");
            myObject.HapusDinamis("daftar_perkara", primaryKey, primaryValue);
            myObject.tampilTabel(Tabledaftar_perkara, SQL, judulkolom);
        } catch (Exception e) {
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Tabledaftar_perkaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabledaftar_perkaraMouseClicked
        // TODO add your handling code here:
            int selectedRow = Tabledaftar_perkara.getSelectedRow();
        if (selectedRow != -1) {
            txtid.setText(Tabledaftar_perkara.getValueAt(selectedRow, 0).toString());
            txtnik_client.setText(Tabledaftar_perkara.getValueAt(selectedRow, 1).toString());
            txtnama_client.setText(Tabledaftar_perkara.getValueAt(selectedRow, 2).toString());
            txtnama_penanggung_jawab.setText(Tabledaftar_perkara.getValueAt(selectedRow, 3).toString());
            txtpenanggung_jawab_kasus.setText(Tabledaftar_perkara.getValueAt(selectedRow, 4).toString());
            txtperkara.setText(Tabledaftar_perkara.getValueAt(selectedRow, 5).toString());
            txtstatus.setText(Tabledaftar_perkara.getValueAt(selectedRow, 6).toString());
            txttindakan_hukum.setText(Tabledaftar_perkara.getValueAt(selectedRow, 7).toString());
            txthasil_tindakan.setText(Tabledaftar_perkara.getValueAt(selectedRow, 8).toString());
            myObject.tampilTabel(Tabledaftar_perkara, SQL, judulkolom);
        }
    }//GEN-LAST:event_Tabledaftar_perkaraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDaftarPerkara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDaftarPerkara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDaftarPerkara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDaftarPerkara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDaftarPerkara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabledaftar_perkara;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txthasil_tindakan;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama_client;
    private javax.swing.JTextField txtnama_penanggung_jawab;
    private javax.swing.JTextField txtnik_client;
    private javax.swing.JTextField txtpenanggung_jawab_kasus;
    private javax.swing.JTextField txtperkara;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttindakan_hukum;
    // End of variables declaration//GEN-END:variables
}
