/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import sys.crudTable;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import ujicoding_2210010455.*;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;






/**
 *
 * @author ALYA NORMAIDA
 */
public class framenilai extends javax.swing.JFrame {
String judulkolom[] = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
int lebarkolom[] = {150, 300, 200, 100, 100, 100};
String SQL = "SELECT *FROM khs";

    /**
     * Creates new form framenilai
     */
    private crudTable myObject;
    public framenilai() {
        initComponents();
        this.setLocationRelativeTo(null);
        myObject = new crudTable();
        myObject.settingJudulTabel(tablenilai, judulkolom);
        myObject.settingLebarKolom(tablenilai, lebarkolom);
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnpm = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtips1 = new javax.swing.JTextField();
        txtips2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtips3 = new javax.swing.JTextField();
        txtips4 = new javax.swing.JTextField();
        txtips5 = new javax.swing.JTextField();
        txtips6 = new javax.swing.JTextField();
        txtips7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenilai = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtipk = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("npm");

        jLabel2.setText("nama");

        jLabel3.setText("ips 1");

        jLabel4.setText("ips 2");

        txtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpmActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel5.setText("ips 3");

        jLabel6.setText("ips 4");

        jLabel7.setText("ips 5");

        jLabel8.setText("ips 6");

        jLabel9.setText("ips 7");

        txtips4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtips4ActionPerformed(evt);
            }
        });

        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tablenilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablenilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenilai);

        jLabel10.setText("ipk");

        jButton4.setText("bersih");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtips1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtips2)
                                    .addComponent(txtips3)
                                    .addComponent(txtips4)
                                    .addComponent(txtips5)
                                    .addComponent(txtips6)
                                    .addComponent(txtips7)
                                    .addComponent(txtipk, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtips1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtips2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtips3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtips4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtips5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtips6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtips7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpmActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void tablenilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenilaiMouseClicked
    int row = tablenilai.getSelectedRow(); // Mendapatkan baris yang diklik
        if (row != -1) { // Pastikan ada baris yang dipilih
        // Mengambil data dari tabel berdasarkan baris yang dipilih
        String npm = tablenilai.getValueAt(row, 0).toString();
        String nama = tablenilai.getValueAt(row, 1).toString();
        String ips1 = tablenilai.getValueAt(row, 2).toString();
        String ips2 = tablenilai.getValueAt(row, 3).toString();
        String ips3 = tablenilai.getValueAt(row, 4).toString();
        String ips4 = tablenilai.getValueAt(row, 5).toString();
        String ips5 = tablenilai.getValueAt(row, 6).toString();
        String ips6 = tablenilai.getValueAt(row, 7).toString();
        String ips7 = tablenilai.getValueAt(row, 8).toString();
        String ipk = tablenilai.getValueAt(row, 9).toString();
        
        // Mengisi data ke TextField
        txtnpm.setText(npm);
        txtnama.setText(nama);
        txtips1.setText(ips1);
        txtips2.setText(ips2);
        txtips3.setText(ips3);
        txtips4.setText(ips4);
        txtips5.setText(ips5);
        txtips6.setText(ips6);
        txtips7.setText(ips7);
        txtipk.setText(ipk);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_tablenilaiMouseClicked

    private void txtips4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtips4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtips4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Simpan data ke database menggunakan fungsi CRUD dinamis
        String[] fields = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            npm,
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };
        myObject.SimpanDinamis("khs", fields, values);

        // Tampilkan IPK ke text field atau area lain di GUI
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan! IPK: " + ipk);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            String primaryKey = "npm";
            String primaryValue = txtnpm.getText();
            
            txtnpm.setText("");
            txtnama.setText("");
            txtips1.setText("");
            txtips2.setText("");
            txtips3.setText("");
            txtips4.setText("");
            txtips5.setText("");
            txtips6.setText("");
            txtips7.setText("");
            txtipk.setText("");
            myObject.HapusDinamis("khs", primaryKey, primaryValue);
            myObject.tampilTabel(tablenilai, SQL, judulkolom);
        } catch (Exception e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung ulang IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Data yang akan diupdate
        String[] fields = {"nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };

        // Update data menggunakan fungsi CRUD dinamis
        String[] isiPrimary = {"npm"}; 
            myObject.UbahDinamis("khs", "npm", txtnpm.getText(), fields, values);

        // Tampilkan kembali data ke tabel
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
            String primaryKey = "npm";
            String primaryValue = txtnpm.getText();
            
            txtnpm.setText("");
            txtnama.setText("");
            txtips1.setText("");
            txtips2.setText("");
            txtips3.setText("");
            txtips4.setText("");
            txtips5.setText("");
            txtips6.setText("");
            txtips7.setText("");
            txtipk.setText("");
        } catch (Exception e) {
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try {
            String laporanfile = "src/cetak/reportKHS.jrxml";
            String SQL = "SELECT * FROM khs";
            
            myObject.tampilLaporan(laporanfile, SQL);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framenilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablenilai;
    private javax.swing.JTextField txtipk;
    private javax.swing.JTextField txtips1;
    private javax.swing.JTextField txtips2;
    private javax.swing.JTextField txtips3;
    private javax.swing.JTextField txtips4;
    private javax.swing.JTextField txtips5;
    private javax.swing.JTextField txtips6;
    private javax.swing.JTextField txtips7;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnpm;
    // End of variables declaration//GEN-END:variables
}
